### PR TITLE
Redesign & clean up

### PR DESCRIPTION
**Pull request by llui85**
Hi there,

Here's my draft implementation of the website redesign. [Here's a live copy](https://airyxos-staging-llui85.pages.dev/) of it. What are your overall thoughts?

## Summary of changes
- I've changed the way that the templates work, instead of having `header.html` and `footer.html`, we now just have `template.html` which the layout is contained in. I've also updated the Makefile to deal with this as well.
- I've cleaned up some invalid HTML in the template.
- Semantic elements such as `<header>`, `<footer>`, `<aside>`, <nav>, and `<code>` are now used in place of the divs.
- I've tweaked the internal layout a lot, so everything's using flexbox or grid now which makes it a bit more maintainable.
- The site is now responsive - the right-hand navigation collapses below the content.
- The new logo and assets have been added. I've taken the background off the header for now so that we can use the two-tone logo.
- The header's been shrunk a bit
- Dark colour scheme support!
- The footer has been given a slight redesign with a background colour.
- I've removed the `bodycontent` function from `airyx.js` - it wasn't used anywhere.
- Indentation was a bit mixed across files, that's been fixed.

## Screenshots
**Home page:**
Screenshot from 2021-09-17 18-43-19
**Screenshots page:**
Screenshot from 2021-09-17 18-44-09
**Release notes page:**
Screenshot from 2021-09-17 18-43-29
Screenshot from 2021-09-17 18-43-35

Live site: https://airyxos-staging-llui85.pages.dev/

Note that this isn't so much a "redesign", more of a general cleanup that lays the base for a redesign.

### CODE REVIEW

**Comment by mszoek** [comment]
This is awesome! A great start and feel free to redesign my styles etc.

**Comment by mszoek** [comment]
Are you OK with me merging this or did you want to work on it some more?

**Comment by llui85** [comment]
Sure! I'll just merge the changes made by @nayaabkhan into my branch.

**Comment by mszoek** [comment]
Can you also please change the wiki link to `https://airyx.miraheze.org/wiki/Main_Page`? Thanks!

**Comment by llui85** [comment]
Sorry for the delay - The Makefile [uses GNU syntax](https://www.gnu.org/software/make/manual/html_node/File-Function.html), so I need to convert that so it can runs on freeBSD.

**Comment by llui85** [comment]
@mszoek This is now ready for merge.

**Pull request merged**
