### PR TITLE
Airyx Design

### PR DESCRIPTION
**Pull request by nayaabkhan**
- [x] Social links
- [x] Community: Links the wiki, bug tracker, Discord/Matrix/IRC, discussions.
- [x] Footer: Remove the text at the bottom about the logo belonging to Ravyn Software. Add credits for the logo.
- [x] Footer: Airyx and airyxOS are trademarks and should be mentioned.
- [x] ~Try inverted navbar (dark bg and white fg)~
- [x] Remove the Hacktoberfest link
- [x] "Darwin & macOS® binaries will not run on Airyx, yet." can become "Very trivial Darwin & macOS binaries can now run on airyxOS, and we're actively working on this!"
- [x] Could we also remove the Spotlight section or move it to the bottom of the page? That coverage is getting stale now so maybe not something to draw attention to.
- [x] Twitter feed
- [x] Something weird with the screenshot formatting in Firefox on macOS
- [x] Finish other pages besides the homepage
- [ ] Test in a UXP based browser

### CODE REVIEW

**Comment by mszoek** [comment]
Are you still working on this @nayaabkhan ?

**Comment by nayaabkhan** [comment]
Hey @mszoek, sorry for the lack of updates recently. I took a break from any kind of work last month. You should see some activity here soon.

**Comment by mszoek** [comment]
No worries! Just checking in :)

**Comment by mszoek** [comment]
Hey! It is looking _awesome_! A couple of things I noticed:
- remove the Hacktoberfest link on main page since that's over for this year
- "Darwin & macOS® binaries will not run on Airyx, yet." can become "Very trivial Darwin & macOS binaries can now run on airyxOS, and we're actively working on this!"
- Something weird with the screenshot formatting in Firefox on macOS

Could we also remove the Spotlight section or move to the bottom of the page? That coverage is getting stale now so maybe not something to draw attention to.

Oh and you'll need to merge in the changes from `main` :)

**Pull request merged**
